"""残局 / 战术题库（30+，均经规则引擎校验）。"""
from __future__ import annotations

PUZZLES: list[dict] = [
    {
        "id": "mate_rook_a0d0",
        "title": "单车锁宫",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "3k5/9/9/9/9/9/9/9/9/R3K4 w - - 0 1",
        "solution": ["a0d0"],
        "hint": "车平到将的直线。",
    },
    {
        "id": "mate_rook_b0d0",
        "title": "肋车绝杀",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "3k5/9/9/9/9/9/9/9/9/1R2K4 w - - 0 1",
        "solution": ["b0d0"],
        "hint": "车贴将门锁死。",
    },
    {
        "id": "mate_rook_c0d0",
        "title": "近车绝杀",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "3k5/9/9/9/9/9/9/9/9/2R1K4 w - - 0 1",
        "solution": ["c0d0"],
        "hint": "车平肋道。",
    },
    {
        "id": "mate_rook_h0f0",
        "title": "右侧锁宫",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "5k3/9/9/9/9/9/9/9/9/4K2R1 w - - 0 1",
        "solution": ["h0f0"],
        "hint": "车平到将的直线。",
    },
    {
        "id": "mate_rook_g0f0",
        "title": "右肋绝杀",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "5k3/9/9/9/9/9/9/9/9/4K1R2 w - - 0 1",
        "solution": ["g0f0"],
        "hint": "车贴将肋。",
    },
    {
        "id": "mate_rook_e1d1",
        "title": "中车平移杀",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "3k5/9/9/9/9/9/9/9/4R4/4K4 w - - 0 1",
        "solution": ["e1d1"],
        "hint": "车平到将的直线。",
    },
    {
        "id": "mate_rook_a1d1",
        "title": "边车平肋",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "3k5/9/9/9/9/9/9/9/R8/4K4 w - - 0 1",
        "solution": ["a1d1"],
        "hint": "车横移锁宫。",
    },
    {
        "id": "mate_rook_i1d1",
        "title": "右边车锁宫",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "3k5/9/9/9/9/9/9/9/8R/4K4 w - - 0 1",
        "solution": ["i1d1"],
        "hint": "车长途平到肋道。",
    },
    {
        "id": "mate_rook_e2d2",
        "title": "高车平移",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "3k5/9/9/9/9/9/9/4R4/9/4K4 w - - 0 1",
        "solution": ["e2d2"],
        "hint": "车平肋将军成杀。",
    },
    {
        "id": "mate_rook_e4d4",
        "title": "巡河车杀",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "3k5/9/9/9/9/4R4/9/9/9/4K4 w - - 0 1",
        "solution": ["e4d4"],
        "hint": "车平肋。",
    },
    {
        "id": "mate_rook_e1f1",
        "title": "中车右锁",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "5k3/9/9/9/9/9/9/9/4R4/4K4 w - - 0 1",
        "solution": ["e1f1"],
        "hint": "车平到将的直线。",
    },
    {
        "id": "mate_rook_i0f0",
        "title": "底线右车",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "5k3/9/9/9/9/9/9/9/9/4K3R w - - 0 1",
        "solution": ["i0f0"],
        "hint": "车平肋锁宫。",
    },
    {
        "id": "mate_rook_a1f1",
        "title": "边车右锁",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "5k3/9/9/9/9/9/9/9/R8/4K4 w - - 0 1",
        "solution": ["a1f1"],
        "hint": "车平到将的直线。",
    },
    {
        "id": "mate_rook_i1f1",
        "title": "右边车右锁",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "5k3/9/9/9/9/9/9/9/8R/4K4 w - - 0 1",
        "solution": ["i1f1"],
        "hint": "车平肋。",
    },
    {
        "id": "mate_rook_e2f2",
        "title": "高车右移杀",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "5k3/9/9/9/9/9/9/4R4/9/4K4 w - - 0 1",
        "solution": ["e2f2"],
        "hint": "车平肋成杀。",
    },
    {
        "id": "mate_rook_e4f4",
        "title": "巡河右锁",
        "goal": "红方一步杀",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "5k3/9/9/9/9/4R4/9/9/9/4K4 w - - 0 1",
        "solution": ["e4f4"],
        "hint": "车平到将的直线。",
    },
    {
        "id": "mate_king_support",
        "title": "帅助车杀",
        "goal": "红方一步杀",
        "difficulty": 2,
        "side": "red",
        "category": "endgame",
        "fen": "3k5/9/9/9/9/9/9/9/9/3R1K3 w - - 0 1",
        "solution": ["f0e0"],
        "hint": "帅占中助车锁死将门。",
    },
    {
        "id": "mate_king_support_r",
        "title": "帅助右车",
        "goal": "红方一步杀",
        "difficulty": 2,
        "side": "red",
        "category": "endgame",
        "fen": "5k3/9/9/9/9/9/9/9/9/3K1R3 w - - 0 1",
        "solution": ["d0e0"],
        "hint": "帅占中配合底车。",
    },
    {
        "id": "mate_cannon_e1e9",
        "title": "重炮沉底",
        "goal": "红方一步杀",
        "difficulty": 2,
        "side": "red",
        "category": "puzzle",
        "fen": "4k4/9/4C4/9/9/9/9/9/4C4/4K4 w - - 0 1",
        "solution": ["e1e9"],
        "hint": "后炮借前炮架沉底。",
    },
    {
        "id": "mate_cannon_e2e9",
        "title": "高炮重炮杀",
        "goal": "红方一步杀",
        "difficulty": 2,
        "side": "red",
        "category": "puzzle",
        "fen": "4k4/9/4C4/9/9/9/9/4C4/9/4K4 w - - 0 1",
        "solution": ["e2e9"],
        "hint": "后炮沉底借架。",
    },
    {
        "id": "pawn_side_d8",
        "title": "高兵贴将",
        "goal": "红方横移高兵",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "3k5/4P4/9/9/9/9/9/9/9/4K4 w - - 0 1",
        "solution": ["e8d8", "e8f8"],
        "hint": "过河兵可左右平移逼宫。",
    },
    {
        "id": "pawn_side_f8",
        "title": "高兵右移",
        "goal": "红方兵贴将肋",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "5k3/4P4/9/9/9/9/9/9/9/4K4 w - - 0 1",
        "solution": ["e8f8", "e8d8"],
        "hint": "兵平移控制将门。",
    },
    {
        "id": "pawn_advance_e7",
        "title": "低兵推进",
        "goal": "红方兵前进",
        "difficulty": 1,
        "side": "red",
        "category": "endgame",
        "fen": "4k4/9/4P4/9/9/9/9/9/9/4K4 w - - 0 1",
        "solution": ["e7e8"],
        "hint": "兵继续前进逼宫。",
    },
    {
        "id": "pawn_push_mid",
        "title": "中兵挺进",
        "goal": "红方兵吃卒或挺进",
        "difficulty": 1,
        "side": "red",
        "category": "puzzle",
        "fen": "3k5/9/9/4p4/9/4P4/9/9/9/4K4 w - - 0 1",
        "solution": ["e4e5"],
        "hint": "兵每次只走一格。",
    },
    {
        "id": "capture_horse_c5b7",
        "title": "马踩黑马",
        "goal": "红方吃掉黑马",
        "difficulty": 2,
        "side": "red",
        "category": "puzzle",
        "fen": "3k5/9/1n7/9/2N6/9/9/9/9/4K4 w - - 0 1",
        "solution": ["c5b7"],
        "hint": "马跳到黑马可吃位置。",
    },
    {
        "id": "capture_cannon_e6c7",
        "title": "马踩黑炮",
        "goal": "红方马吃炮",
        "difficulty": 2,
        "side": "red",
        "category": "puzzle",
        "fen": "3k5/9/2c6/4N4/9/9/9/9/9/4K4 w - - 0 1",
        "solution": ["e6c7"],
        "hint": "马跳到炮位。",
    },
    {
        "id": "capture_rook_a0a5",
        "title": "车吃游离车",
        "goal": "红方吃掉黑车",
        "difficulty": 1,
        "side": "red",
        "category": "puzzle",
        "fen": "3k5/9/9/9/r8/9/9/9/9/R4K3 w - - 0 1",
        "solution": ["a0a5"],
        "hint": "车直吃无根黑车。",
    },
    {
        "id": "capture_cannon_h0h7",
        "title": "车吃黑炮",
        "goal": "红方吃掉黑炮",
        "difficulty": 1,
        "side": "red",
        "category": "puzzle",
        "fen": "3k5/9/7c1/9/9/9/9/9/9/4K2R1 w - - 0 1",
        "solution": ["h0h7"],
        "hint": "车直吃无根炮。",
    },
    {
        "id": "capture_advisor",
        "title": "车吃士",
        "goal": "红方车吃黑士",
        "difficulty": 1,
        "side": "red",
        "category": "puzzle",
        "fen": "3ak4/9/9/9/9/9/9/9/9/3R1K3 w - - 0 1",
        "solution": ["d0d9"],
        "hint": "车直冲九宫吃士。",
    },
    {
        "id": "check_give_rook",
        "title": "出车将军",
        "goal": "红方出车将军",
        "difficulty": 1,
        "side": "red",
        "category": "puzzle",
        "fen": "4k4/9/9/9/9/9/9/9/9/R4K3 w - - 0 1",
        "solution": ["a0a9", "a0e0"],
        "hint": "沉底或平中均可将军。",
    },
    {
        "id": "iron_bolt_like",
        "title": "车占中控局",
        "goal": "红方车吃士或占中",
        "difficulty": 2,
        "side": "red",
        "category": "endgame",
        "fen": "3ak4/9/9/9/9/9/9/9/9/3R1K3 w - - 0 1",
        "solution": ["d0d9", "d0e0"],
        "hint": "车吃士或车占中控制。",
    },
    {
        "id": "defend_d9e9",
        "title": "将开肋道",
        "goal": "黑方应将",
        "difficulty": 2,
        "side": "black",
        "category": "puzzle",
        "fen": "3k5/9/9/9/9/9/9/9/9/3R1K3 b - - 0 1",
        "solution": ["d9e9"],
        "hint": "将离开车线，并避开与帅照面。",
    },
    {
        "id": "defend_f9e9",
        "title": "右侧应将",
        "goal": "黑方应将",
        "difficulty": 2,
        "side": "black",
        "category": "puzzle",
        "fen": "5k3/9/9/9/9/9/9/9/9/3K1R3 b - - 0 1",
        "solution": ["f9e9"],
        "hint": "将回到中线避开车。",
    },
    {
        "id": "defend_d9e9_high",
        "title": "高车应将",
        "goal": "黑方应将",
        "difficulty": 2,
        "side": "black",
        "category": "puzzle",
        "fen": "3k5/9/9/9/9/9/9/9/3R5/5K3 b - - 0 1",
        "solution": ["d9e9"],
        "hint": "将离开车线。",
    },
    {
        "id": "defend_block",
        "title": "垫将解杀",
        "goal": "黑方用士垫将或走开",
        "difficulty": 3,
        "side": "black",
        "category": "puzzle",
        "fen": "3k5/4a4/9/9/9/9/9/9/9/3RK4 b - - 0 1",
        "solution": ["d9e9", "e8d7"],
        "hint": "将离开车线，或士斜下垫将。",
    },
    {
        "id": "rook_chase_two",
        "title": "沉底车追击两步",
        "goal": "红方按正解完成两步追击（含黑方应将）",
        "difficulty": 2,
        "side": "red",
        "category": "endgame",
        "fen": "3k5/9/9/9/9/9/9/9/9/R4K3 w - - 0 1",
        # 第一步将军后黑方仅有 d9d8；服务端自动续走对手着，再要求 a9a8
        "solution_lines": [["a0a9", "d9d8", "a9a8"]],
        "hint": "先沉底将军，待黑将下移后再平肋追击。",
    },
]


def solution_lines_of(puzzle: dict) -> list[list[str]]:
    """
    统一答案形态：
    - solution_lines: 多步变例，每条为完整着法序列（含需自动走出的对手着）
    - solution: 单步题的多个可选正确答案（OR），规范化为多条长度为 1 的 line
    """
    raw_lines = puzzle.get("solution_lines")
    if raw_lines:
        return [[str(m).strip().lower() for m in line] for line in raw_lines if line]
    return [[str(m).strip().lower()] for m in (puzzle.get("solution") or []) if m]


def list_puzzles(category: str | None = None) -> list[dict]:
    items = []
    for p in PUZZLES:
        if category and p.get("category") != category:
            continue
        items.append(
            {
                "id": p["id"],
                "title": p["title"],
                "goal": p["goal"],
                "difficulty": p["difficulty"],
                "side": p["side"],
                "category": p.get("category", "puzzle"),
                "hint": p["hint"],
            }
        )
    return items


def get_puzzle(puzzle_id: str) -> dict | None:
    for p in PUZZLES:
        if p["id"] == puzzle_id:
            return p
    return None
